### ISSUE TITLE
masscan扫描完毕后，出现了报错

### ISSUE THREAD

**Issue by Scivous** [starnightcyber/masnmap#1]
![Snipaste_2021-12-17_10-26-50](https://user-images.githubusercontent.com/66907785/146478878-21bf860d-25e3-4b15-8540-b7bbae892d46.png)

**Comment by starnightcyber** [comment]
hi  @Scivous ,
这个可能是由于 Masscan 版本 -oJ 参数输出的 json 文件格式内容不一致导致的。
你需要稍微调整 extract_masscan 中 json 文件解析。
参考第一条回复哈 ~ 
https://www.freebuf.com/sectool/257698.html
